# Policies
# The policies are stored in a CSV file, one policy per row

# Each row contains values for the following columns:

# The first column contains just a hash symbol '#'
# From the documentation: "Any line without a starting '#' is effectively
#   ignored, so can be used as a comment, to help you organize things."

# name - the name of the policy for system reference
# guiname - the in-game name of the policy
# slider - From the docs: "if set to 'default' then the slider for this
#   policy has no specific features. If set to a name, this name is used
#   inside 'sliders.csv'"
# description - for use on in-game policy details screen
# flags - blank, MULTIPLYINCOME, or UNCANCELLABLE
#   From the docs: "UNCANCELLABLE means the cancel button is greyed out
#   and the policy is always implemented at 0.5 strength unless specified
#   at a different level. MULTIPLYINCOME means that when determining the
#   amount of income generated by the policy, the various inputs to the
#   income get multipleid rather than added (see below).

# introduce - political capital cost to introduce policy
# cancel - political capital cost to cancel policy
# raise - political capital cost to raise policy slider
# lower	- political capital cost to lower policy slider

# department - which of the 7 in-game GUI categories the policy falls under
# mincost - base policy cost with slider all the way to the left
# maxcost - base policy cost with slider all the way to the right
# cost multiplier - From the docs: "A series of inputs, separated by [semi-]
#   colons, which determine how we get a 'cost multiplier' for the policy,
#   which is a value by which the final cost of the policy is multiplied.
#   Each entry in the list is either _default_ and a set value or it's an
#   actual effect" (an inward facing, cost effect, rather than outward)
# implementation - how many in-game turns the policy takes to change. From the
#   docs: "This will be adjusted in practice for the competence of the
#   minister in charge of this policy."
# minincome - base policy income with slider all the way to the left
# maxincome - base policy income with slider all the way to the right
# incomemultiplier - From docs: "Exactly the same as Cost Multiplier, except
#   the flag MULTIPLYINCOME under flags can convert this to be a value
#   where the inputs are multiplied together rather than added.

# The next column contains the flag "#Effects"
#   A variable number of columns to the right of this contain effects of
#   this policy on other items in the engine
